#pragma once

namespace nickel {

// Temporary collision group for Vehicle collision. Will remove in future
enum {
    COLLISION_GROUP_GROUND = 1 << 0,
    COLLISION_GROUP_WHEEL = 1 << 1,
    COLLISION_GROUP_CHASSIS = 1 << 2,
    COLLISION_GROUP_OBSTACLE = 1 << 3,
    COLLISION_GROUP_DRIVABLE_OBSTACLE = 1 << 4,

    COLLISION_GROUP_GROUND_AGAINST = COLLISION_GROUP_CHASSIS |
                                     COLLISION_GROUP_OBSTACLE |
                                     COLLISION_GROUP_DRIVABLE_OBSTACLE,
    COLLISION_GROUP_WHEEL_AGAINST = COLLISION_GROUP_WHEEL |
                                    COLLISION_GROUP_CHASSIS |
                                    COLLISION_GROUP_OBSTACLE,
    COLLISION_GROUP_CHASSIS_AGAINST =
        COLLISION_GROUP_GROUND | COLLISION_GROUP_WHEEL |
        COLLISION_GROUP_CHASSIS | COLLISION_GROUP_OBSTACLE |
        COLLISION_GROUP_DRIVABLE_OBSTACLE,
    COLLISION_GROUP_OBSTACLE_AGAINST =
        COLLISION_GROUP_GROUND | COLLISION_GROUP_WHEEL |
        COLLISION_GROUP_CHASSIS | COLLISION_GROUP_OBSTACLE |
        COLLISION_GROUP_DRIVABLE_OBSTACLE,
    COLLISION_GROUP_DRIVABLE_OBSTACLE_AGAINST =
        COLLISION_GROUP_GROUND | COLLISION_GROUP_CHASSIS |
        COLLISION_GROUP_OBSTACLE | COLLISION_GROUP_DRIVABLE_OBSTACLE
};

}  // namespace nickel