/////////////////////////////////////////////////////////////////
// WARNING: THIS FILE GENERATED BY MUSTACHE, DON'T MODIFY IT!! //
/////////////////////////////////////////////////////////////////

#pragma once

#include "nickel/script/binding/runtime.hpp"
#include "nickel/script/binding/context.hpp"
#include "nickel/script/binding/module.hpp"

namespace nickel::script_binding {


void RegisterQJSScript(script::QJSRuntime&);

}