/////////////////////////////////////////////////////////////////
// WARNING: THIS FILE GENERATED BY MUSTACHE, DON'T MODIFY IT!! //
/////////////////////////////////////////////////////////////////

#include "script_binding.hpp"

namespace nickel::script_binding {

void RegisterQJSScript(script::QJSRuntime& runtime) {
    auto& module = runtime.GetContext().NewModule("NickelEngine");
    module.EndModule();
}

}